import MinModulus.CheckerMath.Glue
import MinModulus.CheckerMath.ComparisonBound
import MinModulus.CheckerImpl.Checker

/-!
# `CheckerSound.Defs`: the shared vocabulary of the code-level soundness proof

STATUS: definitions and small proved helpers; no `sorry`. Owned by CS-D (assembly).

Every CheckerSound agent imports **this** file (never `Interfaces.lean`, see there). The
statements the four agents prove are in `CheckerSound/Interfaces.lean`.

## Conventions
* `pv x = x / 2^62`: the real number that a P-value `x : ℕ` stands for.
* `delta0 P`: **the certificate's δ**, `deltaN P p / 10^9` for `p ≤ X = P.PMAX`, `1/2` for
  `p > X` (`= CheckerMath.deltaPairR (deltaCert P)`). Its tilt is exact:
  `tilt (delta0 P) q = 10^9 / (10^9 - deltaN P q)` for `q ≤ X` (`tilt_delta0_of_le`).
  All expectations below use the tilts `tilt (delta0 P)` and uniform caps `fun _ => N`.
* `acutA P q`, `acutB P q`: the exponent cut-offs of the A-part DP (`mkExpLaw q dn 62`, in
  `buildA`) and of the B-part DP (`mkExpLaw q dn 60`, in `BState.addPrime`).
* `N ≥ 65`: the DP arrays are built from untruncated point masses, which equal `Smooth.rho` only
  below the cap; every `acut ≤ 64`, so every DP statement is made for caps `N ≥ 65` and lifted to
  all caps by monotone coupling (`CheckerMath.hingeLoss_le_of_comparison`).

## The contracts between the agents
* `BValid P B S` (CS-B proves it is preserved by `BState.init`/`BState.addPrime`; CS-C uses it;
  CS-D maintains it along the prime loop): `B` is a valid B-part state for the finite set `S` of
  primes `≤ X`.
* `AValid P A S` (CS-B proves it for `buildA`; CS-C uses it): `A` is a valid A-part state for `S`.
* `blockPhase`, `blockCost`, `BlockHyp`, `ETHyp`: the block phase of `run` (CS-A).
Changes to these definitions go through CS-D (tell CS-D; do not edit this file yourself).
-/

namespace MinModulus.CheckerSound

open Finset MinModulus.CheckerImpl MinModulus.CheckerMath MinModulus.Main

/-! ## P-values and the certificate's δ -/

/-- The real number represented by a P-value: `x / 2^62`. -/
noncomputable def pv (x : ℕ) : ℝ := (x : ℝ) / 2 ^ 62

/-- **The certificate's δ**: `deltaN P p / 10^9` for `p ≤ X = P.PMAX`, `1/2` for `p > X`. -/
noncomputable def delta0 (P : Params) : ℕ → ℝ := deltaPairR (deltaCert P)

/-- Exponent cut-off of the A-part DP (`buildA` uses `mkExpLaw q dn 62`). -/
def acutA (P : Params) (q : ℕ) : ℕ := (mkExpLaw q (deltaN P q) 62).acut

/-- Exponent cut-off of the B-part DP (`BState.addPrime` uses `mkExpLaw q dn 60`). -/
def acutB (P : Params) (q : ℕ) : ℕ := (mkExpLaw q (deltaN P q) 60).acut

/-! ## The τ-DP states (contract CS-B → CS-C, maintained by CS-D) -/

/-- **`B` is a valid B-part state for the set `S`** (tilts `tilt (delta0 P)`):
* the primes of `S` are `≤ X`;
* `D[T] ≥ 2^62 · P(τ_S = T, kept)` for `T < D.size` (`TM = D.size - 1`, cut-offs `acutB`), for
  every uniform cap `N ≥ 65`;
* `EB ≥ 2^62 · Π_{q ∈ S} (1 + ν_q/(q-1))` (hence `≥ 2^62 E[τ_S]`, `CheckerMath.meanTau_le`);
* `lost ≥ 2^62 · Σ_{q ∈ S} ν_q q^{-(acutB q + 1)}` (hence `≥ 2^62 P(some v_q > acutB q)`,
  `CheckerMath.expLostProb_le`). -/
structure BValid (P : Params) (B : BState) (S : Finset ℕ) : Prop where
  mem : ∀ q ∈ S, q.Prime ∧ q ≤ P.PMAX
  law : ∀ N, 65 ≤ N → ∀ T, T < B.D.size →
    lawKept S (tilt (delta0 P)) (fun _ => N) (B.D.size - 1) (acutB P) T ≤ pv B.D[T]!
  mean : ∏ q ∈ S, (1 + tilt (delta0 P) q / ((q : ℝ) - 1)) ≤ pv B.EB
  lost : ∑ q ∈ S, tilt (delta0 P) q * ((q : ℝ)⁻¹) ^ (acutB P q + 1) ≤ pv B.lost

/-- **`A` is a valid A-part state for the set `S`** (arrays indexed by `k ≤ KMAX`, `TM = KMAX`,
cut-offs `acutA`, tilts `tilt (delta0 P)`, every uniform cap `N ≥ 65`):
* `up[k] ≥ 2^62 · P(τ_S = k, kept)` for `k ≤ KMAX`;
* `tailA ≥ 2^62 · E[τ_S ; lost]`;
* `up[k] = 0` for `k > kTop`;
* `q^(acutA q + 1) > 2^62` for `q ∈ S` (so every `s_A ≤ X_p ≤ 2^62` has exponents `≤ acutA`). -/
structure AValid (P : Params) (A : AState) (S : Finset ℕ) : Prop where
  law : ∀ N, 65 ≤ N → ∀ k, k ≤ P.KMAX →
    lawKept S (tilt (delta0 P)) (fun _ => N) P.KMAX (acutA P) k ≤ pv A.up[k]!
  lost : ∀ N, 65 ≤ N → lostMass S (tilt (delta0 P)) (fun _ => N) P.KMAX (acutA P) ≤ pv A.tailA
  top : ∀ k, A.kTop < k → A.up[k]! = 0
  acut : ∀ q ∈ S, 2 ^ 62 < q ^ (acutA P q + 1)

/-! ## The block phase (`PX < p ≤ X`) -/

/-- The block phase of `run P`, started from the running moment products `ET2, ET25, ET3`
(in `run P` these are the values after the prime loop, see `run_eq` in `Loop.lean`). -/
def blockPhase (P : Params) (ET2 ET25 ET3 : ℕ) : BlkSt :=
  blockLoop P (sieve P.PMAX) ⟨0, ET2, ET25, ET3, #[]⟩ (P.PX + 1) (P.PMAX + 1)

/-- The per-prime cost of `p > PX` as `costOf` reads it off the blocks (`costOf_of_gt`). -/
def blockCost (blocks : Array BlockRec) (p : ℕ) : ℕ :=
  match blocks.find? (fun b => b.start ≤ p && p < b.stop) with
  | some b => b.val
  | none => 0

/-- Standing hypotheses of the block phase: `δ` is the positive constant `dC/10^9` on `(PX, X]`
(for `fullParams`: `dC = 409200000`). -/
structure BlockHyp (P : Params) (dC : ℕ) : Prop where
  one_le_PX : 1 ≤ P.PX
  PX_le : P.PX ≤ P.PMAX
  dC_pos : 0 < dC
  const : ∀ p, P.PX < p → p ≤ P.PMAX → deltaN P p = dC

/-- The running moment products after the prime loop bound the products of the per-prime
factors over the primes `≤ PX` (CS-D proves this for `run`). -/
structure ETHyp (P : Params) (ET2 ET25 ET3 : ℕ) : Prop where
  two : ∏ q ∈ Nat.primesLE P.PX, pv (fac2 q (deltaN P q)) ≤ pv ET2
  five_halves : ∏ q ∈ Nat.primesLE P.PX, pv (fac25 q (deltaN P q)) ≤ pv ET25
  three : ∏ q ∈ Nat.primesLE P.PX, pv (fac3 q (deltaN P q)) ≤ pv ET3

/-! ## Helpers (proved) -/

theorem pv_nonneg (x : ℕ) : 0 ≤ pv x := by unfold pv; positivity

theorem pv_add (x y : ℕ) : pv (x + y) = pv x + pv y := by
  unfold pv; push_cast; ring

theorem pv_mono {x y : ℕ} (h : x ≤ y) : pv x ≤ pv y := by
  unfold pv
  have : (x : ℝ) ≤ y := by exact_mod_cast h
  exact div_le_div_of_nonneg_right this (by positivity)

theorem pv_ONE : pv ONE = 1 := by
  norm_num [pv, ONE]

theorem pv_zero : pv 0 = 0 := by simp [pv]

/-- `mulUp` rounds up: `pv x · pv y ≤ pv (mulUp x y)`. -/
theorem pv_mul_le_mulUp (x y : ℕ) : pv x * pv y ≤ pv (mulUp x y) := by
  have h := mulUp_spec x y
  rw [ONE_eq] at h
  have h' : (x : ℝ) * y ≤ (mulUp x y : ℝ) * 2 ^ 62 := by exact_mod_cast h
  unfold pv
  rw [div_mul_div_comm, div_le_div_iff₀ (by positivity) (by positivity)]
  nlinarith [pow_pos (two_pos : (0 : ℝ) < 2) 62]

theorem deltaN_le (P : Params) (p : ℕ) : deltaN P p ≤ 450000000 := by
  unfold deltaN
  exact Nat.min_le_right _ _

theorem two_mul_deltaN_le (P : Params) (p : ℕ) : 2 * deltaN P p ≤ 10 ^ 9 := by
  have := deltaN_le P p
  omega

theorem deltaCert_of_le {P : Params} {p : ℕ} (h : p ≤ P.PMAX) :
    deltaCert P p = (deltaN P p, DDEN) := by
  unfold deltaCert
  rw [ite_eq_right_iff.2 fun h' => absurd h' (not_lt.2 h)]

theorem deltaCert_of_gt {P : Params} {p : ℕ} (h : P.PMAX < p) : deltaCert P p = (1, 2) := by
  unfold deltaCert
  exact ite_eq_left h

theorem two_mul_deltaCert_le (P : Params) (p : ℕ) : 2 * (deltaCert P p).1 ≤ (deltaCert P p).2 := by
  unfold deltaCert
  split_ifs
  · decide
  · exact two_mul_deltaN_le P p

theorem delta0_of_le {P : Params} {p : ℕ} (h : p ≤ P.PMAX) :
    delta0 P p = (deltaN P p : ℝ) / 10 ^ 9 := by
  unfold delta0
  rw [deltaPairR_of_eq (deltaCert_of_le h)]
  norm_num [DDEN]

theorem delta0_of_gt {P : Params} {p : ℕ} (h : P.PMAX < p) : delta0 P p = 1 / 2 := by
  unfold delta0
  rw [deltaPairR_of_eq (deltaCert_of_gt h)]
  norm_num

theorem delta0_nonneg (P : Params) (p : ℕ) : 0 ≤ delta0 P p := by
  unfold delta0
  rw [deltaPairR_apply]
  positivity

theorem delta0_le_half (P : Params) (p : ℕ) : delta0 P p ≤ 1 / 2 := by
  unfold delta0
  rw [deltaPairR_apply]
  have h := two_mul_deltaCert_le P p
  have h' : (2 : ℝ) * (deltaCert P p).1 ≤ (deltaCert P p).2 := by exact_mod_cast h
  rcases Nat.eq_zero_or_pos (deltaCert P p).2 with h0 | hpos
  · rw [h0]; simp
  · have hpos' : (0 : ℝ) < (deltaCert P p).2 := by exact_mod_cast hpos
    rw [div_le_iff₀ hpos']
    linarith

/-- The exact tilt: `tilt (delta0 P) q = 10^9 / (10^9 - deltaN P q)` for `q ≤ X`. -/
theorem tilt_delta0_of_le {P : Params} {q : ℕ} (h : q ≤ P.PMAX) :
    tilt (delta0 P) q = (10 ^ 9 : ℝ) / (10 ^ 9 - deltaN P q) := by
  unfold delta0
  rw [tilt_deltaPairR (deltaCert_of_le h) (by have := deltaN_le P q; unfold DDEN; omega)]
  norm_num [DDEN]

theorem delta0_eq_zero_iff {P : Params} {p : ℕ} (h : p ≤ P.PMAX) :
    delta0 P p = 0 ↔ deltaN P p = 0 := by
  rw [delta0_of_le h]
  constructor
  · intro h0
    rcases div_eq_zero_iff.1 h0 with h0 | h0
    · exact_mod_cast h0
    · norm_num at h0
  · intro h0
    rw [h0]
    simp

/-! ## `costOf` -/

theorem costOf_of_le (r : Result) (P : Params) {p : ℕ} (h : p ≤ P.PX) :
    costOf r P p = r.costs.getD p 0 := by
  unfold costOf
  exact ite_eq_left h

theorem costOf_of_gt (r : Result) (P : Params) {p : ℕ} (h : P.PX < p) :
    costOf r P p = blockCost r.blocks p := by
  unfold costOf blockCost
  rw [ite_eq_right (not_le.2 h)]
  rfl

end MinModulus.CheckerSound
